### ISSUE TITLE
Need feedback on possible fix for issue 853

### ISSUE THREAD

**Issue by sarisssa** [redis-rs/redis-rs#878] opened 2023-06-28 22:29 UTC
Hi All,

Apologies if this is the wrong way to do this but I've posted some thoughts regarding a solution for #853.

Just wondering if I could have some feedback from the community as this is my first OS for redis.

**Comment by jaymell** [comment] 2023-07-12 04:16
Duplicate of #853

**Closed by jaymell** 2023-07-12 04:16 UTC
