### ISSUE TITLE
Slow TLS response with Multiplexed Connection

### ISSUE THREAD

**Issue by artemrakov** [redis-rs/redis-rs#1128] opened 2024-04-02 23:59 UTC
I am trying to store big key in redis around 20MB. However, I am seeing regression when I am trying to `GET` the key with TLS enabled.

* I am using `rustls` and `tokio`
* Only when I enable TLS but works fine without it
* Issue exist only for `GET` commands. For `SET` works fine, no regression in latency
* Also tried `r2d2` pooling without async client. Still seeing the same regression. 
* Only for big keys, but it works fine for smaller ones.

```rust
use std::thread::sleep;
use std::time::{Duration, Instant};

use redis::Client;

#[tokio::main]
async fn main() {
    println!("Connecting to redis");
    let client = Client::open("rediss://127.0.0.1:6379#insecure").unwrap();

    println!("Connected to redis. Starting the loop");
    let value: Vec<u8> = vec![0; 20 * 1024 * 1024]; // 20MB value

    let mut con = client.get_multiplexed_tokio_connection().await.unwrap();
    let _: Result<(), redis::RedisError> = redis::cmd("SET")
        .arg("key")
        .arg(value)
        .query_async(&mut con)
        .await;

    for i in 1..10 {
        let mut con = con.clone();
        let start_time = Instant::now();

        let value: Option<Vec<u8>> = redis::cmd("GET")
             .arg("key")
            .query_async(&mut con)
             .await
             .unwrap();

        let duration = start_time.elapsed().as_millis();
        println!(
            "LoopNumber: {}, RedisGet latency_ms={}, value.is_some()={}",
            i,
            duration,
            value.is_some()
        );

        sleep(Duration::from_secs(1))
    }
}
```

Response:
```
# Cloning connection

Connecting to redis
Connected to redis. Starting the loop
LoopNumber: 1, RedisGet latency_ms=79, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=168, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=162, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=162, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=162, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=161, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=161, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=154, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=162, value.is_some()=true
```

Full repo: https://github.com/artemrakov/redis-tls-issue/tree/main 

Tried to use `bb8` connection [pool](https://github.com/artemrakov/redis-tls-issue/tree/bb8-redis) as well but when connection is called 2 time with big value response is slow.
```
# bb8 connection pool

Connecting to redis
Connected to redis. Starting the loop
LoopNumber: 1, RedisGet latency_ms=81, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=100, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=97, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=91, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=165, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=158, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=152, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=155, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=165, value.is_some()=true
```

**Comment by jaymell** [comment] 2024-04-03 04:40
Hi! I'm not sure exactly what you mean by "regression" here -- are you actually seeing faster performance with TLS-enabled `GET`s via some other means? 

Also, are you able to post a comparison of timings with non-TLS-enabled connections?

**Comment by artemrakov** [comment] 2024-04-03 05:44
Hi! Regression occurs when comparing the first request to the second and subsequent requests, leading to nearly double the initial latency from 88ms to 168ms. I am not sure why this is happening and how to keep it around 88ms.


I dont believe there is a problem with redis server when using ﻿redis-cli, the response time is approximately 44ms with TLS.

non-TLS timings:

```
Connecting to redis
Connected to redis. Starting the loop
LoopNumber: 1, RedisGet latency_ms=19, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=46, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=38, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=22, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=38, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=38, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=27, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=37, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=24, value.is_some()=true
```

**Comment by nihohit** [comment] 2024-04-03 13:19
Do you see different results of you use native tls? Which version of rustls
do you use?

**Comment by nihohit** [comment] 2024-04-04 09:00
> Using redis cli inside ubuntu:

is `redis-host` the same remote ElastiCache server? If so, it's alarming that the numbers for both RustTLS & native TLS are almost 2 orders of magnitude higher than they are for `redis-cli`. In general, you shouldn't wait 1-4 seconds for a get request, even with a large output. Could it be that you're running your app in debug mode instead of release?

**Comment by nihohit** [comment] 2024-04-04 09:53
ok, so initial thoughts - 
1. I ran this locally against a local server, and I get this output with rustls:
```
RedisSet latency_ms=19
LoopNumber: 1, RedisGet latency_ms=169, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=368, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=356, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=351, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=370, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=366, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=368, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=351, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=402, value.is_some()=true
```

Also, `redis-cli` is much faster locally - `0.01s user 0.01s system 76% cpu 0.034 total` - 34 ms are an order of magnitude less than what I see with redis-rs.
I tried "breaking" the parser by not copying the result to a vector - it didn't change the results significantly, which align with the fact that we don't see this with non-tls requests.
@djc, any thoughts from the TLS expert?

In case someone is as lazy as I am, here's a test that sets up the cluster and runs the check - 
```rs
    #[test]
    fn perf() {
        println!("Connecting to redis");
        let ctx = TestContext::new();
        println!("{}", ctx.server.client_addr());

        println!("Connected to redis. Starting the loop");
        let value: Vec<u8> = vec![0; 20 * 1024 * 1024]; // 20MB value

        let mut con = ctx.connection();
        let start_time = Instant::now();
        let _: Result<(), redis::RedisError> =
            redis::cmd("SET").arg("key").arg(value).query(&mut con);
        let duration = start_time.elapsed().as_millis();
        println!("RedisSet latency_ms={}", duration,);

        for i in 1..10 {
            let start_time = Instant::now();

            let value: Option<Vec<u8>> = redis::cmd("GET").arg("key").query(&mut con).unwrap();

            let duration = start_time.elapsed().as_millis();
            println!(
                "LoopNumber: {}, RedisGet latency_ms={}, value.is_some()={}",
                i,
                duration,
                value.is_some()
            );

            sleep(Duration::from_secs(1))
        }
    }
```
you can run it with `REDISRS_SERVER_TYPE=tcp+tls cargo test --all-features --release perf -- --nocapture`

**Comment by ctz** [comment] 2024-04-04 10:29
copy-paste from discord:

[11:12] ctz: nagles?
[11:20] ctz: to expand: nagle's algorithm is on by default for TCP connections and can add tens or hundreds of milliseconds extra latency for small-message protocols like redis. looks like it gets turned off in redis-rs for plain TCP connections, but not for TLS? i could be misreading the code though.
[11:21] ctz: also looks like the TCP behaviour is controlled by a crate feature `tcp_nodelay`
[11:27] ctz: i suggest concentrating getting the non-tcp latency to a local server down to an reasonable level first (significantly less than 1ms -- redis _should_ be able to do hundreds of thousands of gets per second)

**Comment by nihohit** [comment] 2024-04-04 10:39
Nagles was a good hypothesis, but I tested this with & without the `tcp_nodelay` feature, and the results are the same.

Also, I think that the issue isn't even related to TLS - I increased the size of the message to 500MB, and saw a similar effect with non-TLS connections - 
```
RedisSet size=500000000 latency_ms=272
LoopNumber: 1, size=500000000 RedisGet latency_ms=1202, value.is_some()=true
LoopNumber: 2, size=500000000 RedisGet latency_ms=2459, value.is_some()=true
LoopNumber: 3, size=500000000 RedisGet latency_ms=2499, value.is_some()=true
LoopNumber: 4, size=500000000 RedisGet latency_ms=2550, value.is_some()=true
```

Onwards, to `perf`!

**Comment by nihohit** [comment] 2024-04-04 12:04
`perf` puts the responsibility on the parser - looks like something in `combine::stream::decoder::Decoder<S,P,C>::__before_parse` gets slower on the 2nd call and onwards. focus on the `testapp::loop_get` function.

1 call:
![1call](https://github.com/redis-rs/redis-rs/assets/4604038/aa53a4b9-c771-4ef2-8603-121e22ee20b7)
2 calls:
![2calls](https://github.com/redis-rs/redis-rs/assets/4604038/6c0bbf9d-4299-4e22-89d0-0f3489571132)
1 call with TLS:
![1calltls](https://github.com/redis-rs/redis-rs/assets/4604038/00d6632c-e992-4151-80f4-38364c918514)
2 calls with TLS:
![2callstls](https://github.com/redis-rs/redis-rs/assets/4604038/563a373f-f812-44d4-8321-456ca8764a0e)


sample app:

```rs
mod support;
use std::time::Instant;

use support::{ServerType, TestContext};

fn loop_get(mut connection: redis::Connection) {
    for i in 1..3 { // change this to 2 for a flamegraph of a partial call.
        let start_time = Instant::now();

        let value: Option<Vec<u8>> = redis::cmd("GET").arg("key").query(&mut connection).unwrap();

        let duration = start_time.elapsed().as_millis();
        println!(
            "LoopNumber: {} RedisGet latency_ms={}, value.is_some()={}",
            i,
            duration,
            value.is_some()
        );
    }
}

fn main() {
    println!("Connecting to redis");
    let ctx = TestContext::new();
    println!("{}", ctx.server.client_addr());

    println!("Connected to redis. Starting the loop");

    let size = if matches!(ServerType::get_intended(), ServerType::TcpTls) {
        20_000_000
    } else {
        500_000_000
    };

    let value: Vec<u8> = vec![0; size]; // 20MB value

    let mut con = ctx.connection();
    let start_time = Instant::now();
    let _: Result<(), redis::RedisError> = redis::cmd("SET").arg("key").arg(value).query(&mut con);
    let duration = start_time.elapsed().as_millis();
    println!("RedisSet size={size} latency_ms={}", duration,);

    loop_get(con);
}

**Comment by Marwes** [comment] 2024-04-04 13:29
Hypothesis why this happens https://github.com/Marwes/combine/issues/364#issuecomment-2037228538 (if true, this seems to be specific to to the sync parser)

**Comment by nihohit** [comment] 2024-04-04 15:17
@artemrakov I couldn't reproduce this with the async connection in non-TLS mode. Can you create a flamegraph of such a reproduction?

in async & TLS mode this does reproduce, so I assume there is some relevant issue here, but the flamegraphs are much harder to read:
multiple GETs:
![asyncpart](https://github.com/redis-rs/redis-rs/assets/4604038/a25d7c52-a432-4c40-aed7-1a1ab27406a0)
single GET:
![asyncfull](https://github.com/redis-rs/redis-rs/assets/4604038/28e8b17e-62b2-42e1-b50a-add86da24939)

**Comment by artemrakov** [comment] 2024-04-04 15:23
> I couldn't reproduce this with the async connection in non-TLS mode. Can you create a flamegraph of such a reproduction?

with sync or async?

**Comment by artemrakov** [comment] 2024-04-04 15:30
Sorry for the confusion. I dont see this issue in async non-TLS mode. Only in TLS mode. I just included non-TLS timing for reference that they are drastically different from TLS ones.

**Comment by nihohit** [comment] 2024-04-04 15:45
I'd like an async of this https://github.com/redis-rs/redis-rs/issues/1128#issuecomment-2033577647 , if possible. The first call there is still half of the time other calls take.
Just to make sure - that was achieved with a non-TLS multiplexed connection?

**Comment by artemrakov** [comment] 2024-04-04 15:48
>  Just to make sure - that was achieved with a non-TLS multiplexed connection?

Yep. 

>I'd like an async of this https://github.com/redis-rs/redis-rs/issues/1128#issuecomment-2033577647 , if possible

Sure will do

**Comment by artemrakov** [comment] 2024-04-04 16:01
@nihohit 

Attaching profiling info with firefox tool: https://share.firefox.dev/43NInZL  (I can share screenshots as well if needed).

Here are my timings for the debug run:
```
Connected to redis. Starting the loop
Redis
LoopNumber: 1, RedisGet latency_ms=26, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=33, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=28, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=47, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=37, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=40, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=31, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=50, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=25, value.is_some()=true
```

**Comment by artemrakov** [comment] 2024-04-04 16:07
Also, tried to run the code without  `sleep`. I see this:

```
Redis
LoopNumber: 1, RedisGet latency_ms=34, value.is_some()=true
LoopNumber: 2, RedisGet latency_ms=19, value.is_some()=true
LoopNumber: 3, RedisGet latency_ms=12, value.is_some()=true
LoopNumber: 4, RedisGet latency_ms=7, value.is_some()=true
LoopNumber: 5, RedisGet latency_ms=6, value.is_some()=true
LoopNumber: 6, RedisGet latency_ms=9, value.is_some()=true
LoopNumber: 7, RedisGet latency_ms=6, value.is_some()=true
LoopNumber: 8, RedisGet latency_ms=7, value.is_some()=true
LoopNumber: 9, RedisGet latency_ms=6, value.is_some()=true
```

**Comment by Marwes** [comment] 2024-04-05 09:19
> https://github.com/redis-rs/redis-rs/issues/1128#issuecomment-2037494699

@nihohit Did you mess up and switch the single/multiple get labels? The data makes more sense the other way around with write_bytes being huge when multiple get are used. If so then that is https://github.com/rustls/tokio-rustls/issues/55 (linked earlier on this PR). They are the same kind of slowdown, just in different crates. Limiting the maximum size to initialize the buffer (as suggested on that issue) seems like the easiest solution, I don't think tokio-rustls can implement precise tracking of which memory is initialized since it doesn't have full control over the buffer.

**Comment by nihohit** [comment] 2024-04-05 10:42
> Did you mess up and switch the single/multiple get labels? 

I did 🤦. thanks for noticing.

**Comment by nihohit** [comment] 2024-06-13 11:29
closing, since these are issues stemming from other crates.

**Closed by nihohit** 2024-06-13 11:29 UTC
