### ISSUE TITLE
Missing blocking commands for Redis Sorted set

### ISSUE THREAD

**Issue by gheorghitamutu** [redis-rs/redis-rs#944] opened 2023-09-03 10:29 UTC
Hello,

I was looking through Sorted Set functions (wrappers over commands) in this library and I noticed that there are no blocking commands exposed for Redis Sorted Set. More specifically:

https://redis.io/commands/bzpopmin
https://redis.io/commands/bzpopmax
https://redis.io/commands/bzmpop

Are there any plans to implement these in the near future?
I also found an issue that's related to this - https://github.com/redis-rs/redis-rs/issues/476 - but there's no answer to it.

It is indeed true that one could just use:
```
let (key, member, score): (String, String, u64) = redis::cmd("BZPOPMIN")
            .arg(key)
            .arg(1)
            .arg(0)
            .query_async(&mut connection)
            .await?;
```

But I was expecting to have a wrapper similar to List blocking commands:

```
    fn blpop<K: ToRedisArgs>(key: K, timeout: usize) {
        cmd("BLPOP").arg(key).arg(timeout)
    }
```

**Comment by nihohit** [comment] 2023-09-07 06:41
> Are there any plans to implement these in the near future?

I don't think any of the maintainers are planning on doing this, but we're always happy to accept contributions. Usually adding commands is very easy.

> I also found an issue that's related to this - https://github.com/redis-rs/redis-rs/issues/476 - but there's no answer to it.

Answered there. Thanks for pointing that out.

**Comment by jaymell** [comment] 2023-09-08 19:12
I'm going to close this as a duplicate of #476, but please feel free to submit a PR if you'd like @gheorghitamutu.

**Closed by jaymell** 2023-09-08 19:12 UTC
