### ISSUE TITLE
Does the crate support RESP3 ? 

### ISSUE THREAD

**Issue by vortex314** [redis-rs/redis-rs#693] opened 2022-10-15 09:25 UTC
The newer RESP3 protocol supports the fact that a single TCP connection is used for command execution and subscriptions at the same time, it's more resource friendly. https://github.com/antirez/RESP3/blob/master/spec.md
When connecting to a redis-server with RESP3 support, it returns an issue indicating that the protocol is unknown.
Is this crate using hiredis library ? Maybe this is using an older version of hiredis. 
This code fails and it shouldn't : 
 ```
                    let res = redis::cmd("HELLO").arg("3").query::<HashMap<String,String>>(&mut con);
```
It returns an error code in the same way an older version of redis-cli would show connecting to a redis-server resp3

**Comment by vortex314** [comment] 2022-10-15 09:37
Answering my own question : 
Stepping into the code it looks that the crate itself is doing the TCP level encoding/decoding, so the answer is NO. 
Any plans then to support RESP3 ?

**Comment by jaymell** [comment] 2022-10-15 20:02
This is a duplicate of #329. We would love to have this functionality in place, however to my knowledge there is no current work being done to address this. PRs are always welcome! :slightly_smiling_face:

**Closed by jaymell** 2022-10-15 20:02 UTC
