### ISSUE TITLE
Error handling results of con.keys("meta_data:*") command

### ISSUE THREAD

**Issue by mark-e-hoffman** [redis-rs/redis-rs#971] opened 2023-10-04 21:02 UTC
Sample code:

 let keys:redis::Value = self.conn.keys("meta_data:814*").unwrap();

When I print it out the shape looks like this:
bulk(bulk(string-data('"127.0.0.1:30002"'), bulk(string-data('"meta_data:81495851"'), string-data('"meta_data:81495855"'), string-data('"meta_data:81495858"'), string-data('"meta_data:81495854"'), string-data('"meta_data:81463177"'), string-data('"meta_data:81463182"'))), bulk(string-data('"127.0.0.1:30001"'), bulk(string-data('"meta_data:81463180"'), string-data('"meta_data:81495852"'), string-data('"meta_data:81463183"'), string-data('"meta_data:81463179"'), string-data('"meta_data:81495856"'), string-data('"meta_data:81463176"'), string-data('"meta_data:81463184"'), string-data('"meta_data:81463175"'))), bulk(string-data('"127.0.0.1:30000"'), bulk(string-data('"meta_data:81463181"'), string-data('"meta_data:81463178"'), string-data('"meta_data:81495857"'), string-data('"meta_data:81463185"'), string-data('"meta_data:81495853"'), string-data('"meta_data:81463174"'))))

When I add a type to the query:
   let keys:Vec<String> = self.conn.keys("meta_data:814*").unwrap();
I get:
 Response was of incompatible type - TypeError: "Response type not string compatible." (response was bulk(string-data('"127.0.0.1:30002"'), bulk(string-data('"meta_data:81495851"'), string-data('"meta_data:81495855"'), string-data('"meta_data:81495858"'), string-data('"meta_data:81495854"'), string-data('"meta_data:81463177"'), string-data('"meta_data:81463182"'))))

I have no idea why the one of the 3 urls to my cluster is being returned and I still can't handle the return data. I've tried multiple variations on the return Type but nothing seems to work.

Thanks

**Comment by nihohit** [comment] 2023-10-05 04:35
Hi, @mark-e-hoffman, can you provide us with a reproducible test?

> I have no idea why the one of the 3 urls to my cluster is being returned

This is an issue with the last release, which will be fixed in the next release.

**Comment by Cheban1996** [comment] 2024-02-15 17:44
```
 redis: Response was of incompatible type - TypeError: "Response type not string compatible." (response was int(1)
 redis: Response was of incompatible type - TypeError: "Response type not bool compatible." (response was string-data('"{\"id\":16,\"devices\":300,\"is_active\":true,\"online\":0}"'))
```
And i don't know how reproduced it
What intersting is errors from prod
but local and staging is good working

**Comment by nihohit** [comment] 2024-03-28 10:48
closing, due to no response.

**Closed by nihohit** 2024-03-28 10:48 UTC
