### ISSUE TITLE
What is the best way to do run transaction from async code  

### ISSUE THREAD

**Issue by eyalsatori** [redis-rs/redis-rs#565] opened 2021-12-09 13:33 UTC
Hi , 

I have a Tokio app that uses the redis-rs, and its need to add a transaction(CAS) call.  
Currently we are using a ConnectionManger object from multiple tasks. 

But  (If I got it correctly), I can't use WATCH command from multiple tasks, as EXEC from one task could cancel WATCH to other tasks- as it run's on the same connection.

Is there any recommended way doing that?

**Comment by Parth** [comment] 2022-01-01 19:40
duplicate of: https://github.com/mitsuhiko/redis-rs/issues/353?

**Comment by nihohit** [comment] 2024-03-25 17:00
Closing as "not planned", since this issue is inherent to the current design and can't be fixed.

**Closed by nihohit** 2024-03-25 17:00 UTC
