### ISSUE TITLE
Getting bytes is slow

### ISSUE THREAD

**Issue by unimonkiez** [redis-rs/redis-rs#803] opened 2023-03-15 14:39 UTC
Hello,
I'm trying to convert some of my code functionality from python to rust for better performance.
Currently I'm setting byte array from (with length of 49,152,000) with SET command, and getting it in python:
```python
start_time = time.time()
my_large_data = redis.get("my_large_data")
print(f"Got the data of length {len(my_large_data)}, that took {time.time() - start_time}s")
```
That prints 
```sh
Got the data of length 49152000, that took 0.7418110370635986s
```

In rust I wrote the same code:
```rust
let start = std::time::Instant::now();
let my_large_data: Vec<u8> = con
    .get("my_large_data")
    .unwrap();
println!(
    "Got the data of length {}, that took {:?}",
    my_large_data.len(),
    start.elapsed()
);
```

That prints 
```sh
Got the data of length 49152000, that took 10.575589667s
```

**Comment by unimonkiez** [comment] 2023-03-15 14:40
Also tried running on NodeJS using `ioredis` and is just as fast as python

**Comment by jaymell** [comment] 2023-03-15 15:57
Thanks for bringing this up. The stats for Rust relative to Python are actually even worse on my local setup :sweat_smile:. I'm not immediately sure where the bottleneck is, but this is definitely something we need to look into.

**Comment by nihohit** [comment] 2023-03-22 09:08
Interesting, this seems to be an issue only with the sync client. 

```rs
#[test]
fn test_time_for_large_value_async() {
    let large_data = vec![1_u8; 49_152_000];
    let key = "foo";
    let ctx = TestContext::new();
    block_on_all(async move {
        let mut conn = ctx.multiplexed_async_connection().await.unwrap();
        let _: () = conn.set(key, &large_data).await.unwrap();
        let start = std::time::Instant::now();
        let my_large_data: Vec<u8> = conn.get(key).await.unwrap();
        println!(
            "ASYNC Got the data of length {}, that took {:?}",
            my_large_data.len(),
            start.elapsed()
        );
    });
}

#[test]
fn test_time_for_large_value_async() {
    let large_data = vec![1_u8; 49_152_000];
    let key = "foo";
    let ctx = TestContext::new();
    block_on_all(async move {
        let mut conn = ctx.multiplexed_async_connection().await.unwrap();
        let _: () = conn.set(key, &large_data).await.unwrap();
        let start = std::time::Instant::now();
        let my_large_data: Vec<u8> = conn.get(key).await.unwrap();
        println!(
            "ASYNC Got the data of length {}, that took {:?}",
            my_large_data.len(),
            start.elapsed()
        );
    });
}
```

prints 
```
SYNC Got the data of length 49152000, that took 4.430667074s
test test_time_for_large_value ... ok

ASYNC Got the data of length 49152000, that took 127.379041ms
test test_time_for_large_value_async ... ok
```

when running against a local server.

**Comment by unimonkiez** [comment] 2023-03-26 12:51
It did help a lot, before I got
```log
Got the data of length 49152000, that took 18.873396792s
```
Now I get this (with @nihohit changes using tokio dependency)
```log
Got the data of length 49152000, that took 1.471552166s
```
But I still get this in python
```log
Got the data of length 49152000, that took 0.5492780208587646s
```

Tried digging in the code myself but I'm a beginner at Rust 🥲

**Comment by nihohit** [comment] 2023-03-26 15:57
I believe the issue is with the parser. I'll try to dive deeper tomorrow. 
@unimonkiez, I'm not sure why you experience 10x slower async work than I do.

**Comment by jaymell** [comment] 2023-03-26 16:22
I think this is likely a long-standing issue. See for example #81, which was closed without a clear resolution.

**Comment by nihohit** [comment] 2023-03-27 06:46
I tried running the same code in release mode, and it took 157ms for the sync connection. @unimonkiez have you benchmarked using debug or release configuration?

**Comment by unimonkiez** [comment] 2023-03-27 09:22
I just created [this repo](https://github.com/unimonkiez/redis-rs-performance), it shows benchmarks the different libraries, and more importantly, how everything is runs.  
<details>
  <summary>Here is the program's output</summary>
  
  ```sh
@@@@@@@@@@@@@ NODEJS @@@@@@@@@@@@@@@@@@@@

> nodejs@1.0.0 start:release
> NODE_PATH=dist/ node ./dist/start.js

Successfully got "my_large_data" of size 49152000, that took 426ms
@@@@@@@@@@@@@ END OF NODEJS @@@@@@@@@@@@@
@@@@@@@@@@@@@ PYTHON @@@@@@@@@@@@@@@@@@@@
Successfully got "my_large_data" of size 49152000, that took 433.3610534667969ms
@@@@@@@@@@@@@ END OF PYTHON @@@@@@@@@@@@@
@@@@@@@@@@@@@ RUST @@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@ DEBUG_SYNC @@@@@@@@@@@@@@@@
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/main`
Successfully got "my_large_data" of size 49152000, that took 16.181963208s
@@@@@@@@@@@@@ END OF DEBUG_SYNC @@@@@@@@@
@@@@@@@@@@@@@ DEBUG_TOKIO @@@@@@@@@@@@@@@
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/main`
Successfully got "my_large_data" of size 49152000, that took 416.236208ms
@@@@@@@@@@@@@ END OF DEBUG_TOKIO @@@@@@@@
@@@@@@@@@@@@@ RELEASE_SYNC @@@@@@@@@@@@@@
Successfully got "my_large_data" of size 49152000, that took 440.910625ms
@@@@@@@@@@@@@ END OF RELEASE_SYNC @@@@@@@
@@@@@@@@@@@@@ RELEASE_TOKIO @@@@@@@@@@@@@
Successfully got "my_large_data" of size 49152000, that took 410.059833ms
@@@@@@@@@@@@@ END OF RELEASE_TOKIO @@@@@@
@@@@@@@@@@@@@ END OF RUST @@@@@@@@@@@@@@@
```
</details>

Or better this way:

| Language | Time [ms] |
| --- | --- |
| NodeJS | 426 |
| Python | 433 |
| Rust Debug Sync | 16181 |
| Rust Debug Tokio | 416 |
| Rust Release Sync | 440 |
| Rust Release Tokio | 410 |

As @nihohit suggested, it seems the only problem is for the sync connection in debug mode.  
Currently I'll be moving forward with the `tokio` solution, since I can't wait that long while developing.
But I would like to see this issue fixed and drop the unnecessary dependency in the future, maybe I'll find the time to do so.

**Comment by altanozlu** [comment] 2023-03-29 17:32
I'd like to try out https://github.com/aembke/fred.rs too since it has another parser

**Comment by nihohit** [comment] 2023-03-30 07:59
great idea, @altanozlu 
If you want to measure differences between parsers, I recommend 2 things - 
1. benchmark only the parsers, not the whole E2E communication with the server. That will remove network / cross process noise from the results.
2. If you do want to compare E2E performance, then don't use a single call, like the sample repo. aggregate the results from multiple calls (I recommend 100,000 or more), and preferably run them only on a single thread. The more calls use the same thread, the more the results are affected by pressure on the CPU, and so the results will be more affected by CPU-bound tasks such as parsing.

**Comment by nihohit** [comment] 2023-09-09 18:20
Closing, as the core issue was found.

**Closed by nihohit** 2023-09-09 18:20 UTC
