### ISSUE TITLE
Panic During Failover for Single Shard AWS Clusters

### ISSUE THREAD

**Issue by kamulos** [redis-rs/redis-rs#1098] opened 2024-03-25 17:46 UTC
AWS allows to create single shard clusters, which sounds a bit weird, but is really nice for money reasons and because it can scale to a bigger cluster smoothly. I have such a cluster containing two nodes (primary and replica) providing a single shard. When I trigger a manual failover, `redis-rs` panics. The panic is caught by `tokio`, but after that `redis-rs` is in a state where it is not able to send commands anymore.

I tried the release 0.25.2, it panicked here: https://github.com/redis-rs/redis-rs/blob/cdc0183dd7dd53da72cce73ab84c3cbb10387e45/redis/src/cluster_async/mod.rs#L758 Also the commit just before the `resp3` merge on the `main` branch exhibits the same issue.

So in general, there is only one connection to my single primary and this machine just vanishes during the failover. I can try to reproduce it locally and dig into the exact sequence of events leading to the panic later this week.

**Comment by nihohit** [comment] 2024-03-25 18:43
This will be problematic to test, since `redis-server` requires at least 3 shards for local cluster.

Does this https://github.com/redis-rs/redis-rs/pull/1099 fix the issue? If it does, which error message do you receive from the request, if at all?

**Comment by nihohit** [comment] 2024-03-26 14:14
I managed to get a single-shard cluster in our test framework, but I can't recreate the issue. @kamulos can you explain the workflow that triggers this issue?

```rust
    #[test]
    fn test_async_cluster_handle_failover_in_single_shard_cluster() {
        let cluster = TestClusterContext::new(6, 1);

        block_on_all(async {
            let mut connection = cluster.async_connection().await;
            let split_to_lines = |value| {
                String::from_owned_redis_value(value)
                    .unwrap()
                    .split('\n')
                    .filter_map(|line| {
                        if line.is_empty() {
                            None
                        } else {
                            Some(line.to_string())
                        }
                    })
                    .collect::<Vec<_>>()
            };

            // In this section, we will find out all of the nodes which don't belong in the shard containing slot 0.
            // Slot 0 isn't particulary important - we just choose an arbitrary slot.
            let mut cluster_node_cmd = cmd("CLUSTER");
            cluster_node_cmd.arg("NODES");
            let route_to_primary = RoutingInfo::SingleNode(SingleNodeRoutingInfo::SpecificNode(
                Route::new(0, redis::cluster_routing::SlotAddr::Master),
            ));
            let route_to_replica = RoutingInfo::SingleNode(SingleNodeRoutingInfo::SpecificNode(
                Route::new(0, redis::cluster_routing::SlotAddr::ReplicaRequired),
            ));
            let nodes = connection
                .route_command(&cluster_node_cmd, route_to_primary.clone())
                .await?;
            let lines = split_to_lines(nodes);
            let node_id_to_data: HashMap<_, _> = lines
                .iter()
                .filter_map(|line| line.split_once(" 127.0.0.1:"))
                .collect();
            // This gives us the node id of the primary we contacted.
            let primary_node_id = node_id_to_data
                .iter()
                .find(|(_, value)| value.contains("myself"))
                .unwrap()
                .0;

            // we forget all nodes that aren't the primary or its replica.
            let nodes_to_forget = node_id_to_data.iter().filter_map(|(node_id, data)| {
                if node_id == primary_node_id || data.contains(primary_node_id) {
                    None
                } else {
                    Some(node_id)
                }
            });
            for node_id in nodes_to_forget {
                let mut cluster_forget_cmd = cmd("CLUSTER");
                cluster_forget_cmd.arg("FORGET").arg(node_id);
                assert_eq!(
                    connection
                        .route_command(&cluster_forget_cmd, route_to_primary.clone())
                        .await?,
                    Value::Okay
                );
                assert_eq!(
                    connection
                        .route_command(&cluster_forget_cmd, route_to_replica.clone())
                        .await?,
                    Value::Okay
                );
            }

            // we verify that both the primary and the replica only know each other, and no other node in the cluster.
            let primary_node_view = connection
                .route_command(&cluster_node_cmd, route_to_primary.clone())
                .await?;
            let replica_node_view = connection
                .route_command(&cluster_node_cmd, route_to_replica.clone())
                .await?;
            assert_eq!(split_to_lines(primary_node_view).len(), 2);
            assert_eq!(split_to_lines(replica_node_view).len(), 2);

            // add all missing slots to the shard. We use the fact that we know that the cluster is 3 shards to start from the first known slot in other shards
            let mut cluster_add_slots_cmd = cmd("CLUSTER");
            cluster_add_slots_cmd.arg("ADDSLOTS");
            for i in 5461..16384 {
                cluster_add_slots_cmd.arg(i);
            }
            assert_eq!(
                connection
                    .route_command(&cluster_add_slots_cmd, route_to_primary.clone())
                    .await?,
                Value::Okay
            );

            // now we have a full single shard cluster, so we create a new connection, that is unaware of the removed shards.
            let ip: u16 = node_id_to_data
                .get(primary_node_id)
                .unwrap()
                .split('@')
                .next()
                .unwrap()
                .parse()
                .unwrap();
            let client = ClusterClient::builder(vec![format!("redis://localhost:{ip}")])
                .use_protocol(use_protocol())
                .build()
                .unwrap();
            let mut connection = client.get_async_connection().await.unwrap();

            // FAILOVER from primary to replica
            let mut cluster_failover_cmd = cmd("CLUSTER");
            cluster_failover_cmd.arg("FAILOVER");
            assert_eq!(
                connection
                    .route_command(&cluster_failover_cmd, route_to_replica.clone())
                    .await?,
                Value::Okay
            );

            // this should trigger a topology refresh
            let mut set_cmd = cmd("SET");
            set_cmd
                .arg("test")
                .arg("test_data")
                .query_async(&mut connection)
                .await?;
            // This is sent to "multiple nodes", which in practice is only 1 node - we use this codepath to reproduce the issue in https://github.com/redis-rs/redis-rs/issues/1098
            let result = connection
                .route_command(
                    &set_cmd,
                    RoutingInfo::MultiNode((
                        MultipleNodeRoutingInfo::AllMasters,
                        Some(ResponsePolicy::AllSucceeded),
                    )),
                )
                .await?;
            assert_eq!(result, Value::Okay);

            Ok(())
        })
        .unwrap();
    }

**Comment by kamulos** [comment] 2024-03-26 14:25
### The Issue

Thanks for the quick fix :) This works flawlessly: there is no panic and after ~18s I have a working connection again.

During that time I get a lot of "No nodes found for multi-node operation",  and no instance of the second error.

### Single Node Cluster

Regarding a single node cluster: I found a script, which I used in the past to get a single node cluster:

```
cluster set-config-epoch 1
cluster meet 127.0.0.1 6379
cluster addslotsrange 0 16383
```

But I just saw, that you also found a way.

### How to Reproduce without AWS

I'll analyze the logs and get back to you. The situation in AWS is special I guess, because the failover is not friendly, but the master instance is ripped out of the cluster. So even if you try contacting it you will just end up in timeouts.

I think it is unrelated to this issue, but there is also the thing, that the initial contact DNS name is dynamic and points to any valid node. But if you ask the cluster for its nodes none of the names matches the initial contact DNS name.

**Comment by kamulos** [comment] 2024-03-26 14:27
Maybe in this case there is no need for a replica instance. As long as the master stops responding, this issue might be triggered. Will try to find a way to reproduce...

**Comment by nihohit** [comment] 2024-03-26 16:09
Ok, so if it's fine with you, I'll wait until there's a working test before merging this - I'll give it a week or 2, to see if I can find something to make this work, and worst-case, we'll merge this without a test.

**Comment by nihohit** [comment] 2024-04-02 15:29
Fix merged without tests.

**Closed by nihohit** 2024-04-02 15:29 UTC

**Comment by nihohit** [comment] 2024-04-04 07:29
0.25.3 released

**Comment by kamulos** [comment] 2024-04-04 10:06
Thank you for all your work :heart:
