### ISSUE TITLE
Variable-length mget response

### ISSUE THREAD

**Issue by jonhoo** [redis-rs/redis-rs#336] opened 2020-06-08 19:50 UTC
The current API allows you to do an `MGET` using `conn.get(keys)` where `keys` is a `&[T: ToRedisValue]`. However, it's not clear (at least to me) how to get the _values_ from such a lookup. If I _know_ the number of keys, I can do:
```rust
assert_eq!(keys.len(), 2);
let (v1, v2): (i32, i32) = conn.get(keys)
```
But this doesn't work if `keys` is of variable length.

My first instinct was to do
```rust
let values: Vec<i32> = conn.get(keys)
```

But that fails with:
```
Response was of incompatible type: "Response type not vector compatible." (response was string-data('"0"'))
```

Is there a way to achieve this with the current API (except by doing single lookups or ignoring the result entirely)?

**Comment by jonhoo** [comment] 2020-06-08 19:56
I think what's actually happening here is that I was accidentally passing a vector of length 1, and in _that_ case the command isn't an `MGET`, and so the response isn't an array. This is a pretty surprising and tricky-to-debug outcome. I wonder if the "automatic MGET" should always be put into effect when given a list of keys, even if the list length happens to be 1.

**Comment by Terkwood** [comment] 2020-06-09 14:13
I agree that the current strategy of returning a single value when passed a vector of keys is counter-intuitive.  I think that this would be worth making a breaking change to the API, as you suggest.

There's a good argument in the other direction, too, since breaking changes will disrupt users.

**Comment by xiaodonng** [comment] 2020-11-09 13:57
came across the same issue.
agree with @jonhoo that the return value should correspond to the passed vector, most of the times the length of the vector can only be determined during runtime. This should be an issue which is very easy bumping into.

**Comment by dacioromero** [comment] 2020-12-17 00:45
Ran into this issue myself and attempted to reproducible example of this issue: https://github.com/dacioromero/redis-rs-vec

I believe the culprits are the following:

https://github.com/mitsuhiko/redis-rs/blob/1d14ce077f305043bb71e029bad8f97ab8867461/src/commands.rs#L280-L282

https://github.com/mitsuhiko/redis-rs/blob/1d14ce077f305043bb71e029bad8f97ab8867461/src/types.rs#L805-L807

https://github.com/mitsuhiko/redis-rs/blob/1d14ce077f305043bb71e029bad8f97ab8867461/src/types.rs#L682-L685

It might be as simple as always treating `Vec`s and maybe even slices as multiple arguments, though it could be an annoying breaking change for people who were relying on this behavior.

For now I'm just going to use `redis::cmd("MGET")` instead.

**Comment by mihai1voicescu** [comment] 2021-09-14 14:11
Any news on this? The API is very counter intuitive in this case, and it takes a while to figure out the problem...

If the breaking change is the problem maybe a separate MGET command and documenting this behaviour in the get docs would also be fine.

**Comment by kMeillet** [comment] 2021-12-03 12:01
This is very unintuitive and make deserialization a pain. Hope this get merged soon.

**Comment by vamshiaruru-virgodesigns** [comment] 2022-11-26 04:08
+1 on this. Just ran into it and was very surprised.

**Closed** 2022-12-19 09:17 UTC
