### ISSUE TITLE
Response's value does not match the expected command's response value 

### ISSUE THREAD

**Issue by x1qqq** [redis-rs/redis-rs#1017] opened 2024-01-03 01:26 UTC
I am having an issue with this library when trying to fetch a json object via the function `json_get`.
It outputs the following error logs.

![image](https://github.com/redis-rs/redis-rs/assets/87322933/84221a84-72c8-40bc-8289-2ae58e4cf4d0)

Eventually after a few tries, it manages to fetch the correct value, but it always has this unexpected behavior for around 2 or 3 times with the same following values: int(1),  ok

I have no idea where the problem is coming from, I am supposing there might be a problem with the library, I just don't know what it specifically can be.

Note:
I am using the ConnectionManager.
I am using redis-macros for implementing FromRedisValue via its derive macro for my struct object `InteractionStep`.

**Comment by jaymell** [comment] 2024-01-03 06:06
Can you post a reproducible example?

**Comment by x1qqq** [comment] 2024-01-03 10:50
I have tried reproducing on a test function, everything seems to be working fine there somehow.

The only difference from my code and the test function, is that I'm passing the ConnectionManager to a [TypeMap](https://docs.rs/typemap_rev/latest/typemap_rev/struct.TypeMap.html#), everything else functionality wise is the same.

To give a little bit more context on what I am doing, I am building a discord bot with [serenity-rs](https://docs.rs/serenity/latest/serenity/) and using this library (redis-rs) to fetch json objects.

Here is my test function

```rust
#[cfg(test)]
mod tests {
    use std::time::Duration;

    use redis::aio::ConnectionLike;
    use redis::{aio::ConnectionManager, JsonAsyncCommands};
    use serenity::all::InteractionType;

    use crate::database::{InteractionStepKind, InteractionStep};
    use crate::slash_command::SlashCommandFunctionality;
    use crate::payload::captcha::UpdateSettings;
        

    #[tokio::test]
    async fn redis_json_get() {
        // Init redis
        let host = "127.0.0.1";
        let port = 6379;
        let user = "default";
        let password = "development";
        let database = 0;

        let client = redis::Client::open(format!("redis://{}:{}@{}:{}/{}", user, password, host, port, database)).unwrap();
        let mut conn_manager = ConnectionManager::new_with_backoff(client, 2, 2, 5).await.unwrap();

        let object = InteractionStep::new(
            &ulid::Ulid::new().to_string(),
            InteractionStepKind::ConfirmAction { confirm_button_id: "aaa".to_string(), cancel_button_id: "bbb".to_string() },
            SlashCommandFunctionality::UpdateCaptchaSettings(UpdateSettings { enabled: false, verified_role_id: Some(0000000), unverified_role_id: Some(111111) }),
            InteractionType::Component,
            00000000000000,
        );

        // JSON.SET
        let mut pipeline = redis::pipe();
        pipeline.json_set(&object.id, "$", &object).unwrap()
            .cmd("EXPIRE").arg(&object.id).arg(60).ignore();
        conn_manager.req_packed_commands(&pipeline, 0, 2).await.unwrap();
       

        tokio::time::sleep(Duration::from_secs(30)).await;

        // JSON.GET
        let object_fetched : InteractionStep = conn_manager.json_get(&object.id, "$").await.unwrap();

        assert_eq!(object, object_fetched)
    }
}
```

**Comment by x1qqq** [comment] 2024-01-04 11:16
I seem to have found the issue, I am not aware of what it is specifically but.

There might be something wrong with the implementation of JsonAsyncCommands for ConnectionManager.

This was my previous function wrapper over json_get, which was giving me the unexpected behavior above
![image](https://github.com/redis-rs/redis-rs/assets/87322933/ec76f007-c840-4a2b-9fc1-b4f7687ac4bf)

As soon as I removed the generic parameter and defined the type as ConnectionManager, things started working as expected again.

![image](https://github.com/redis-rs/redis-rs/assets/87322933/b2b41f0e-5fc0-46ff-8dae-fa2672291339)

**Comment by nihohit** [comment] 2024-01-05 05:44
Yes, the `req_packed_commands` arguments are a bit volatile - essentially, mostly the offset & count arguments have only 2 correct options - either (0, <num of commands>) for non-atomic pipelines, or (<num of commands> + 1, 1) for atomic pipelines. Ignored commands don't matter here.
It seems to me like the function was intended to be internal to the crate, and is supposed to be used in the pipeline's `query/query_async` function.

@jaymell  We can definitely improve the command's documentation to reflect this, but if we're ok with breaking backwards compatibility about this, IMO we should hide this function from the users. It's a bit of a footgun.

**Comment by x1qqq** [comment] 2024-01-06 14:54
@nihohit Thanks for the information, yeah its definitely a bit confusing.
I wasn't aware that ignoring commands on the pipeline wouldn't count when using that same pipeline in the `req_packed_commands`.
So from what I understood, calling the `ignore()` function on a command, only works as intended when `query/query_async` pipeline's functions are called, is that right?

**Comment by nihohit** [comment] 2024-01-06 16:41
@x1qqq query/query_async/execute are the correct interfaces.

**Comment by nihohit** [comment] 2024-01-24 19:15
@x1qqq, can this issue be closed?

**Comment by mrjackwills** [comment] 2024-02-07 07:34
I am also experiencing a similar error, I am trying to create a simple example at the moment.

**Comment by nihohit** [comment] 2024-02-07 08:10
@mrjackwills are you also using `req_packed_commands`?

**Comment by mrjackwills** [comment] 2024-02-07 08:15
> @mrjackwills are you also using `req_packed_commands`?

No, I'm using the simple `AsyncCommands`. I am trying to debug at the moment, I think my issue might be related to the TTL command, but there are many layers to try to delve through.

**Comment by mrjackwills** [comment] 2024-02-07 08:53
Ok, so I have finally worked out the issue, I was using the wrong connection type. 

I should have been using a `ConnectionManager` rather then `Connection`. As this connection is being shared in a multi-threaded API backend. So far, this seems to have solved the issues I was having.

**Comment by nihohit** [comment] 2024-02-16 07:51
@Cheban1996 what's the issue? Int isn't string compatible, and strings aren't bool compatible.

**Comment by Cheban1996** [comment] 2024-02-16 10:33
@nihohit It was noticed that there are no problems at low loads. But when the load is heavy, instead of the expected data for a certain type, we get something completely different - as if from a different pool.
For greater understanding, I also use bb8-redis = "0.14.0" to pull threads. It looks like the problem is related to out of sync responses between threads. When we expect one thing and get another from another stream

**Comment by nihohit** [comment] 2024-02-16 11:36
what connection type do you use?
if it's `aio::Connection`, it's deprecated - use `aio::MultiplexedConnection`.

**Comment by Cheban1996** [comment] 2024-02-16 18:25
@nihohit Thank you so much
It's resolve my trouble

**Comment by nihohit** [comment] 2024-03-25 06:12
Resolving, as this issue seems to have been answered.

**Closed by nihohit** 2024-03-25 06:12 UTC
